# Generated by Django 5.0.6 on 2024-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('image_url', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
